# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bdf0f745486ca79eaffb4d723b4d0b1fc471ec682c3b7b708e0d0222c974a6f81d7e39884493ef5ab6f20513f12c530bade3c92b51a7bc5fe7bcf2a3c936380

test:
  secret_key_base: 541452425e4eebe38732d7a2878f9159dc1e385e8691b7b202f8bb0541927301ac2ad9579a3613ed17c28530efe08869881852321f709afa445384a80952030e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
